var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.Be||(h.Be=0);h.Be++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(n,p,t){var q=new XMLHttpRequest;q.open("GET",n,!0);q.responseType="arraybuffer";q.onprogress=function(u){var x=p;u.total&&(x=u.total);if(u.loaded){q.Nd?h.ee[n].loaded=u.loaded:(q.Nd=!0,h.ee||(h.ee={}),h.ee[n]={loaded:u.loaded,total:x});var P=x=u=0,X;for(X in h.ee){var Y=h.ee[X];u+=Y.total;x+=Y.loaded;P++}u=Math.ceil(u*h.Be/P);h.setStatus&&h.setStatus(`Downloading data... (${x}/${u})`)}else!h.ee&&h.setStatus&&h.setStatus("Downloading data...")};
q.onerror=function(){throw Error("NetworkError for: "+n);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)t(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,x,P){this.start=u;this.end=x;this.audio=P}function p(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
u=new Uint8Array(u);n.prototype.ye=u;u=a.files;for(var x=0;x<u.length;++x)n.prototype.Nd[u[x].filename].onload();h.removeRunDependency("datafile_tetrism.data")}h.FS_createPath("/","font",!0,!0);n.prototype={Nd:{},open:function(u,x){this.name=x;this.Nd[x]=this;h.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.ye.subarray(this.start,this.end))},finish:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency(`fp ${this.name}`);this.Nd[this.name]=null}};
for(var t=a.files,q=0;q<t.length;++q)(new n(t[q].start,t[q].end,t[q].audio||0)).open("GET",t[q].filename);h.addRunDependency("datafile_tetrism.data");h.Ze||(h.Ze={});h.Ze["tetrism.data"]={Vf:!1};m?(p(m),m=null):g=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+
"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("tetrism.data",""):"tetrism.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/font/AldotheApache.ttf",
start:0,end:17092}],remote_package_size:17092});var aa=Object.assign({},h),ba="./this.program",ca=(a,b)=>{throw b;},da="",ea,fa,ha;"undefined"!=typeof document&&document.currentScript&&(da=document.currentScript.src);da=0!==da.indexOf("blob:")?da.substr(0,da.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
fa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};ha=a=>{document.title=a};var ia=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.thisProgram&&(ba=h.thisProgram);h.quit&&(ca=h.quit);var ja;h.wasmBinary&&(ja=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&l("no native wasm support detected");
var ka,r,la=!1,ma,v,w,na,oa,y,z,A,pa,B,C,qa=[],ra=[],sa=[],ta=[],ua=[];function va(){var a=h.preRun.shift();qa.unshift(a)}var wa=0,xa=null,ya=null;function za(){wa++;h.monitorRunDependencies&&h.monitorRunDependencies(wa)}function Aa(){wa--;h.monitorRunDependencies&&h.monitorRunDependencies(wa);if(0==wa&&(null!==xa&&(clearInterval(xa),xa=null),ya)){var a=ya;ya=null;a()}}
function l(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";k(a);la=!0;ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ba(a){return a.startsWith("data:application/octet-stream;base64,")}var Ca;Ca="tetrism.wasm";if(!Ba(Ca)){var Da=Ca;Ca=h.locateFile?h.locateFile(Da,da):da+Da}function Ea(a){if(a==Ca&&ja)return new Uint8Array(ja);throw"both async and sync fetching of the wasm failed";}
function Fa(a){return ja||"function"!=typeof fetch?Promise.resolve().then(()=>Ea(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a))}function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k("failed to asynchronously prepare wasm: "+d);l(d)})}
function Ha(a,b){var c=Ca;ja||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}
var Ka={283616:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,283763:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,283997:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Md||("undefined"!==typeof AudioContext?b.Md=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Md=new webkitAudioContext),b.Md&&
Ia(b.Md));return void 0===b.Md?-1:0},284490:()=>h.SDL2.Md.sampleRate,284558:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.le&&(clearTimeout(g.capture.le),g.capture.le=void 0);g.capture.se=g.Md.createMediaStreamSource(m);g.capture.Qd=g.Md.createScriptProcessor(b,a,1);g.capture.Qd.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ae=n.inputBuffer,n=[d],C.get(c).apply(null,n))};g.capture.se.connect(g.capture.Qd);g.capture.Qd.connect(g.Md.destination);
g.capture.stream=m}var g=h.SDL2;g.capture.ve=g.Md.createBuffer(a,b,g.Md.sampleRate);g.capture.ve.getChannelData(0).fill(0);g.capture.le=setTimeout(function(){g.capture.Ae=g.capture.ve;var m=[d];C.get(c).apply(null,m)},b/g.Md.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},286210:(a,b,c,
d)=>{var e=h.SDL2;e.audio.Qd=e.Md.createScriptProcessor(b,0,a);e.audio.Qd.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Oe=f.outputBuffer,f=[d],C.get(c).apply(null,f))};e.audio.Qd.connect(e.Md.destination)},286620:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ae.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ae.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ja(a+
4*g,f[g]);else for(g=0;g<b;++g)Ja(a+4*(g*d+e),f[g])}},287225:(a,b)=>{for(var c=h.SDL2,d=c.audio.Oe.numberOfChannels,e=0;e<d;++e){var f=c.audio.Oe.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=A[a+(g*d+e<<2)>>2]}},287705:a=>{var b=h.SDL2;if(a){void 0!==b.capture.le&&clearTimeout(b.capture.le);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.Qd&&(b.capture.Qd.onaudioprocess=function(){},b.capture.Qd.disconnect(),b.capture.Qd=void 0);void 0!==b.capture.se&&(b.capture.se.disconnect(),b.capture.se=void 0);void 0!==b.capture.ve&&(b.capture.ve=void 0);b.capture=void 0}else void 0!=b.audio.Qd&&(b.audio.Qd.disconnect(),b.audio.Qd=void 0),b.audio=void 0;void 0!==b.Md&&void 0===b.audio&&void 0===b.capture&&(b.Md.close(),b.Md=void 0)},288877:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.hf!==h.canvas&&
(d.Vd=h.createContext(h.canvas,!1,!0),d.hf=h.canvas);if(d.w!==a||d.h!==b||d.tf!==d.Vd)d.image=d.Vd.createImageData(a,b),d.w=a,d.h=b,d.tf=d.Vd;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=y[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.lf!==a&&(d.kf=new Int32Array(a.buffer),d.mf=new Uint8Array(a.buffer),d.lf=a),a=d.kf,c=a.length,a.set(y.subarray(b,b+c)),a=d.mf,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Vd.putImageData(d.image,0,0)},290346:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var p=y[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&
255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(y.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,w,d,c.length+1);return d},291335:a=>{h.canvas&&(h.canvas.style.cursor=a?F(w,a):"")},291418:()=>{h.canvas&&(h.canvas.style.cursor="none")},291487:()=>window.innerWidth,291517:()=>window.innerHeight};
function La(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ma=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ia=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Ma(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Na=a=>{for(;0<a.length;)a.shift()(h)};
function Ja(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":v[a>>0]=b;break;case "i8":v[a>>0]=b;break;case "i16":na[a>>1]=b;break;case "i32":y[a>>2]=b;break;case "i64":pa[a>>3]=BigInt(b);break;case "float":A[a>>2]=b;break;case "double":B[a>>3]=b;break;case "*":z[a>>2]=b;break;default:l(`invalid type for setValue: ${c}`)}}
var Oa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Pa=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ra=a=>
{if("/"===a)return"/";a=Pa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Sa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);l("initRandomDevice")},Ta=a=>(Ta=Sa())(a);
function Ua(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Oa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Wa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Wa)return Wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Xa=[],Ya=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Za(a){var b=Array(Ya(a)+1);a=E(a,b,0,b.length);b.length=a;return b}var $a=[];function ab(a,b){$a[a]={input:[],Pd:[],Zd:b};bb(a,cb)}
var cb={open:function(a){var b=$a[a.node.ue];if(!b)throw new G(43);a.Kd=b;a.seekable=!1},close:function(a){a.Kd.Zd.oe(a.Kd)},oe:function(a){a.Kd.Zd.oe(a.Kd)},read:function(a,b,c,d){if(!a.Kd||!a.Kd.Zd.Qe)throw new G(60);for(var e=0,f=0;f<d;f++){try{var g=a.Kd.Zd.Qe(a.Kd)}catch(m){throw new G(29);}if(void 0===g&&0===e)throw new G(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Kd||!a.Kd.Zd.Fe)throw new G(60);try{for(var e=0;e<d;e++)a.Kd.Zd.Fe(a.Kd,
b[c+e])}catch(f){throw new G(29);}d&&(a.node.timestamp=Date.now());return e}},db={Qe:function(){a:{if(!Xa.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Xa=Za(a)}a=Xa.shift()}return a},Fe:function(a,b){null===b||10===b?(ia(F(a.Pd,0)),a.Pd=[]):0!=b&&a.Pd.push(b)},oe:function(a){a.Pd&&0<a.Pd.length&&(ia(F(a.Pd,0)),a.Pd=[])},wf:function(){return{Nf:25856,
Pf:5,Mf:191,Of:35387,Lf:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},xf:function(){return 0},yf:function(){return[24,80]}},eb={Fe:function(a,b){null===b||10===b?(k(F(a.Pd,0)),a.Pd=[]):0!=b&&a.Pd.push(b)},oe:function(a){a.Pd&&0<a.Pd.length&&(k(F(a.Pd,0)),a.Pd=[])}},gb=a=>{a=65536*Math.ceil(a/65536);var b=fb(65536,a);b?(w.fill(0,b,b+a),a=b):a=0;return a};
function hb(a,b){var c=a.Hd?a.Hd.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Hd,a.Hd=new Uint8Array(b),0<a.Ld&&a.Hd.set(c.subarray(0,a.Ld),0))}
var H={Wd:null,Yd(){return H.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);H.Wd||(H.Wd={dir:{node:{be:H.Id.be,Rd:H.Id.Rd,ie:H.Id.ie,te:H.Id.te,af:H.Id.af,xe:H.Id.xe,bf:H.Id.bf,$e:H.Id.$e,we:H.Id.we},stream:{de:H.Jd.de}},file:{node:{be:H.Id.be,Rd:H.Id.Rd},stream:{de:H.Jd.de,read:H.Jd.read,write:H.Jd.write,Ke:H.Jd.Ke,Ee:H.Jd.Ee,We:H.Jd.We}},link:{node:{be:H.Id.be,Rd:H.Id.Rd,ke:H.Id.ke},stream:{}},Ne:{node:{be:H.Id.be,Rd:H.Id.Rd},stream:ib}});
c=jb(a,b,c,d);16384===(c.mode&61440)?(c.Id=H.Wd.dir.node,c.Jd=H.Wd.dir.stream,c.Hd={}):32768===(c.mode&61440)?(c.Id=H.Wd.file.node,c.Jd=H.Wd.file.stream,c.Ld=0,c.Hd=null):40960===(c.mode&61440)?(c.Id=H.Wd.link.node,c.Jd=H.Wd.link.stream):8192===(c.mode&61440)&&(c.Id=H.Wd.Ne.node,c.Jd=H.Wd.Ne.stream);c.timestamp=Date.now();a&&(a.Hd[b]=c,a.timestamp=c.timestamp);return c},Xf(a){return a.Hd?a.Hd.subarray?a.Hd.subarray(0,a.Ld):new Uint8Array(a.Hd):new Uint8Array(0)},Id:{be(a){var b={};b.Tf=8192===(a.mode&
61440)?a.id:1;b.Zf=a.id;b.mode=a.mode;b.dg=1;b.uid=0;b.Yf=0;b.ue=a.ue;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ld:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Jf=new Date(a.timestamp);b.bg=new Date(a.timestamp);b.Sf=new Date(a.timestamp);b.gf=4096;b.Kf=Math.ceil(b.size/b.gf);return b},Rd(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ld!=b))if(0==b)a.Hd=null,a.Ld=0;else{var c=a.Hd;a.Hd=new Uint8Array(b);
c&&a.Hd.set(c.subarray(0,Math.min(b,a.Ld)));a.Ld=b}},ie(){throw kb[44];},te(a,b,c,d){return H.createNode(a,b,c,d)},af(a,b,c){if(16384===(a.mode&61440)){try{var d=lb(b,c)}catch(f){}if(d)for(var e in d.Hd)throw new G(55);}delete a.parent.Hd[a.name];a.parent.timestamp=Date.now();a.name=c;b.Hd[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},xe(a,b){delete a.Hd[b];a.timestamp=Date.now()},bf(a,b){var c=lb(a,b),d;for(d in c.Hd)throw new G(55);delete a.Hd[b];a.timestamp=Date.now()},$e(a){var b=[".",".."],
c;for(c in a.Hd)a.Hd.hasOwnProperty(c)&&b.push(c);return b},we(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},ke(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},Jd:{read(a,b,c,d,e){var f=a.node.Hd;if(e>=a.node.Ld)return 0;a=Math.min(a.node.Ld-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Hd||a.Hd.subarray)){if(f)return a.Hd=b.subarray(c,c+d),a.Ld=
d;if(0===a.Ld&&0===e)return a.Hd=b.slice(c,c+d),a.Ld=d;if(e+d<=a.Ld)return a.Hd.set(b.subarray(c,c+d),e),d}hb(a,e+d);if(a.Hd.subarray&&b.subarray)a.Hd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Hd[e+f]=b[c+f];a.Ld=Math.max(a.Ld,e+d);return d},de(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ld);if(0>b)throw new G(28);return b},Ke(a,b,c){hb(a.node,b+c);a.node.Ld=Math.max(a.node.Ld,b+c)},Ee(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);a=a.node.Hd;if(e&2||
a.buffer!==v.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=gb(b);if(!b)throw new G(48);v.set(a,b)}else c=!1,b=a.byteOffset;return{Bf:b,ff:c}},We(a,b,c,d){H.Jd.write(a,b,0,d,c,!1);return 0}}},mb=(a,b,c)=>{var d=`al ${a}`;fa(a,e=>{e||l(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Aa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&za(d)},nb=h.preloadPlugins||[];
function ob(a,b,c,d){"undefined"!=typeof pb&&qb();var e=!1;nb.forEach(function(f){!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e}function rb(a,b,c,d,e,f,g,m,n,p){function t(x){function P(X){p&&p();m||sb(a,b,X,d,e,n);f&&f();Aa(u)}ob(x,q,P,()=>{g&&g();Aa(u)})||P(x)}var q=b?Ua(Pa(a+"/"+b)):a,u=`cp ${q}`;za(u);"string"==typeof c?mb(c,x=>t(x),g):t(c)}function tb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,G=null,kb={},Cb=(a,b={})=>{a=Ua(a);if(!a)return{path:"",node:null};b=Object.assign({Pe:!0,Ge:0},b);if(8<b.Ge)throw new G(32);a=a.split("/").filter(g=>!!g);for(var c=vb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=lb(c,a[e]);d=Pa(d+"/"+a[e]);c.je&&(!f||f&&b.Pe)&&(c=c.je.root);if(!f||b.Ce)for(f=0;40960===(c.mode&61440);)if(c=Bb(d),d=Ua(Qa(d),c),c=Cb(d,{Ge:b.Ge+1}).node,40<f++)throw new G(32);}return{path:d,node:c}},Db=a=>{for(var b;;){if(a===
a.parent)return a=a.Yd.Ve,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},Eb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length},lb=(a,b)=>{var c;if(c=(c=Fb(a,"x"))?c:a.Id.ie?0:2)throw new G(c,a);for(c=zb[Eb(a.id,b)];c;c=c.fe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Id.ie(a,b)},jb=(a,b,c,d)=>{a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.fe=zb[b];return zb[b]=a},Hb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+=
"w");return b},Fb=(a,b)=>{if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ib=(a,b)=>{try{return lb(a,b),20}catch(c){}return Fb(a,"wx")},Jb=()=>{for(var a=0;4096>=a;a++)if(!xb[a])return a;throw new G(33);},Kb=a=>{a=xb[a];if(!a)throw new G(8);return a},Mb=(a,b=-1)=>{Lb||(Lb=function(){this.Nd={}},Lb.prototype={},Object.defineProperties(Lb.prototype,{object:{get(){return this.node},set(c){this.node=c}},
flags:{get(){return this.Nd.flags},set(c){this.Nd.flags=c}},position:{get(){return this.Nd.position},set(c){this.Nd.position=c}}}));a=Object.assign(new Lb,a);-1==b&&(b=Jb());a.fd=b;return xb[b]=a},ib={open:a=>{a.Jd=wb[a.node.ue].Jd;a.Jd.open&&a.Jd.open(a)},de:()=>{throw new G(70);}},bb=(a,b)=>{wb[a]={Jd:b}},Nb=(a,b)=>{var c="/"===b,d=!b;if(c&&vb)throw new G(10);if(!c&&!d){var e=Cb(b,{Pe:!1});b=e.path;e=e.node;if(e.je)throw new G(10);if(16384!==(e.mode&61440))throw new G(54);}b={type:a,gg:{},Ve:b,
Af:[]};a=a.Yd(b);a.Yd=b;b.root=a;c?vb=a:e&&(e.je=b,e.Yd&&e.Yd.Af.push(b))},I=(a,b,c)=>{var d=Cb(a,{parent:!0}).node;a=Ra(a);if(!a||"."===a||".."===a)throw new G(28);var e=Ib(d,a);if(e)throw new G(e);if(!d.Id.te)throw new G(63);return d.Id.te(d,a,b,c)},Ob=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return I(a,b|8192,c)},Pb=(a,b)=>{if(!Ua(a))throw new G(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new G(44);b=Ra(b);var d=Ib(c,b);if(d)throw new G(d);if(!c.Id.we)throw new G(63);c.Id.we(c,b,a)},Qb=a=>
{var b=Cb(a,{parent:!0}).node;if(!b)throw new G(44);var c=Ra(a);a=lb(b,c);a:{try{var d=lb(b,c)}catch(f){d=f.ae;break a}var e=Fb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new G(d);if(!b.Id.xe)throw new G(63);if(a.je)throw new G(10);b.Id.xe(b,c);b=Eb(a.parent.id,a.name);if(zb[b]===a)zb[b]=a.fe;else for(b=zb[b];b;){if(b.fe===a){b.fe=a.fe;break}b=b.fe}},Bb=a=>{a=Cb(a).node;if(!a)throw new G(44);if(!a.Id.ke)throw new G(28);return Ua(Db(a.parent),a.Id.ke(a))},Rb=(a,b)=>{a="string"==typeof a?
Cb(a,{Ce:!0}).node:a;if(!a.Id.Rd)throw new G(63);a.Id.Rd(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Tb=(a,b,c)=>{if(""===a)throw new G(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Pa(a);try{e=Cb(a,{Ce:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new G(20);}else e=I(a,c,0),d=!0;
if(!e)throw new G(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new G(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Hb(b)||b&512)?31:Fb(e,Hb(b)):44))throw new G(c);if(b&512&&!d){c=e;c="string"==typeof c?Cb(c,{Ce:!0}).node:c;if(!c.Id.Rd)throw new G(63);if(16384===(c.mode&61440))throw new G(31);if(32768!==(c.mode&61440))throw new G(28);if(d=Fb(c,"w"))throw new G(d);c.Id.Rd(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Mb({node:e,path:Db(e),
flags:b,seekable:!0,position:0,Jd:e.Jd,Ff:[],error:!1});e.Jd.open&&e.Jd.open(e);!h.logReadFiles||b&1||(Sb||(Sb={}),a in Sb||(Sb[a]=1));return e},Ub=a=>{if(null===a.fd)throw new G(8);a.De&&(a.De=null);try{a.Jd.close&&a.Jd.close(a)}catch(b){throw b;}finally{xb[a.fd]=null}a.fd=null},Vb=(a,b,c)=>{if(null===a.fd)throw new G(8);if(!a.seekable||!a.Jd.de)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.Jd.de(a,b,c);a.Ff=[]},Wb=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new G(28);if(null===a.fd)throw new G(8);
if(0===(a.flags&2097155))throw new G(8);if(16384===(a.node.mode&61440))throw new G(31);if(!a.Jd.write)throw new G(28);a.seekable&&a.flags&1024&&Vb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new G(70);b=a.Jd.write(a,b,c,d,e,f);g||(a.position+=b);return b},Xb=()=>{G||(G=function(a,b){this.name="ErrnoError";this.node=b;this.Df=function(c){this.ae=c};this.Df(a);this.message="FS error"},G.prototype=Error(),G.prototype.constructor=G,[44].forEach(a=>{kb[a]=new G(a);kb[a].stack=
"<generic error, no stack>"}))},Yb,Zb=(a,b)=>{a="string"==typeof a?a:Db(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Pa(a+"/"+c);try{I(d,16895,0)}catch(e){}a=d}}return d},$b=(a,b,c,d)=>{a=Pa(("string"==typeof a?a:Db(a))+"/"+b);c=tb(c,d);return I(a,(void 0!==c?c:438)&4095|32768,0)},sb=(a,b,c,d,e,f)=>{var g=b;a&&(a="string"==typeof a?a:Db(a),g=b?Pa(a+"/"+b):a);a=tb(d,e);g=I(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<
e;++d)b[d]=c.charCodeAt(d);c=b}Rb(g,a|146);b=Tb(g,577);Wb(b,c,0,c.length,0,f);Ub(b);Rb(g,a)}return g},J=(a,b,c,d)=>{a=Pa(("string"==typeof a?a:Db(a))+"/"+b);b=tb(!!c,!!d);J.Te||(J.Te=64);var e=J.Te++<<8|0;bb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,g,m,n)=>{for(var p=0,t=0;t<n;t++){try{var q=c()}catch(u){throw new G(29);}if(void 0===q&&0===p)throw new G(6);if(null===q||void 0===q)break;p++;g[m+t]=q}p&&(f.node.timestamp=Date.now());return p},write:(f,g,m,n)=>
{for(var p=0;p<n;p++)try{d(g[m+p])}catch(t){throw new G(29);}n&&(f.node.timestamp=Date.now());return p}});return Ob(a,b,e)},ac=a=>{if(!(a.Se||a.zf||a.link||a.Hd)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ea)try{a.Hd=Za(ea(a.url)),a.Ld=a.Hd.length}catch(b){throw new G(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");
}},bc=(a,b,c,d,e)=>{function f(n,p,t,q,u){n=n.node.Hd;if(u>=n.length)return 0;q=Math.min(n.length-u,q);if(n.slice)for(var x=0;x<q;x++)p[t+x]=n[u+x];else for(x=0;x<q;x++)p[t+x]=n.get(u+x);return q}if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Se:!1,url:c};var g=$b(a,b,d,e);c.Hd?g.Hd=c.Hd:c.url&&(g.Hd=null,g.url=c.url);Object.defineProperties(g,{Ld:{get:function(){return this.Hd.length}}});
var m={};Object.keys(g.Jd).forEach(n=>{var p=g.Jd[n];m[n]=function(){ac(g);return p.apply(null,arguments)}});m.read=(n,p,t,q,u)=>{ac(g);return f(n,p,t,q,u)};m.Ee=(n,p,t)=>{ac(g);var q=gb(p);if(!q)throw new G(48);f(n,v,q,p,t);return{Bf:q,ff:!0}};g.Jd=m;return g},cc={},Lb,Sb,dc=void 0;function ec(){dc+=4;return y[dc-4>>2]}
function fc(a,b){gc=a;hc=b;if(ic)if(jc||(jc=!0),0==a)kc=function(){var d=Math.max(0,lc+b-mc())|0;setTimeout(nc,d)};else if(1==a)kc=function(){oc(nc)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}kc=function(){setImmediate(nc)}}}var mc;mc=()=>performance.now();
function pc(a,b,c,d,e){!ic||l("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ic=a;qc=d;var f=rc;jc=!1;nc=function(){if(!la)if(0<sc.length){var g=Date.now(),m=sc.shift();m.Wf(m.If);if(tc){var n=tc,p=0==n%1?n-1:Math.floor(n);tc=m.Rf?p:(8*n+(p+.5))/9}ia('main loop blocker "'+m.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||"Please wait...",
m=tc,n=uc.Uf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));f<rc||setTimeout(nc,0)}else if(!(f<rc))if(vc=vc+1|0,1==gc&&1<hc&&0!=vc%hc)kc();else{0==gc&&(lc=mc());if(!(la||h.preMainLoop&&!1===h.preMainLoop())){if(!la)try{a(),wc()}catch(t){xc(t)}h.postMainLoop&&h.postMainLoop()}f<rc||("object"==typeof SDL&&SDL.audio&&SDL.audio.Cf&&SDL.audio.Cf(),kc())}};e||(b&&0<b?fc(0,1E3/b):fc(1,1),kc());if(c)throw"unwind";}
var xc=a=>{a instanceof La||"unwind"==a||ca(1,a)},yc=a=>{ma=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);la=!0}ca(a,new La(a))},wc=()=>{if(!noExitRuntime)try{var a=ma;ma=a;yc(a)}catch(b){xc(b)}},zc=a=>{setTimeout(()=>{if(!la)try{a(),wc()}catch(b){xc(b)}},1E4)},jc=!1,kc=null,rc=0,ic=null,qc=0,gc=0,hc=0,vc=0,sc=[],uc={},lc,nc,tc,Ac=!1,Bc=!1,Cc=[];
function qb(){function a(){Bc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Dc){Dc=!0;nb.push({canHandle:function(c){return!h.fg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Ec(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Ec(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{n.complete||l("Image "+
d+" could not be decoded");var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{ia("Image "+m+" could not be decoded");f&&f()};n.src=m}});nb.push({canHandle:function(c){return!h.eg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e&&e(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Ec(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);
n.onerror=function(){if(!g){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var p="",t=0,q=0,u=0;u<c.length;u++)for(t=t<<8|c[u],q+=8;6<=q;){var x=t>>q-6&63;q-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==q?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==q&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+
";base64,"+p;f(n)}};n.src=m;zc(()=>{f(n)})}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Bc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Fc(a,b,c,d){if(b&&h.Vd&&a==h.canvas)return h.Vd;var e;if(b){var f={antialias:!1,alpha:!1,Ue:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Gc&&(e=Hc(a,f)))var m=K[e].$d}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof L||l("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.Vd=m,b&&Ic(e),h.Gf=b,Cc.forEach(n=>n()),qb());return m}var Jc=!1,Kc=void 0,Lc=void 0;
function Mc(a,b){function c(){Ac=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Nc,Kc&&d.requestPointerLock(),Ac=!0,Lc?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),Oc(h.canvas),Pc()):Oc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Lc?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]&
-8388609),Oc(h.canvas),Pc()):Oc(d));if(h.onFullScreen)h.onFullScreen(Ac);if(h.onFullscreen)h.onFullscreen(Ac)}Kc=a;Lc=b;"undefined"==typeof Kc&&(Kc=!0);"undefined"==typeof Lc&&(Lc=!1);var d=h.canvas;Jc||(Jc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Nc(){if(!Ac)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Qc=0;function oc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Qc)Qc=b+1E3/60;else for(;b+2>=Qc;)Qc+=1E3/60;setTimeout(a,Math.max(Qc-b,0))}}
function Ec(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Rc=[];function Pc(){var a=h.canvas;Rc.forEach(b=>b(a.width,a.height))}
function Oc(a,b,c){b&&c?(a.Hf=b,a.sf=c):(b=a.Hf,c=a.sf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Lc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var pb={},Dc,M=12288,Sc=!1,Tc=0,Uc=0,Vc=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},Wc={},Xc;function Yc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function Zc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function $c(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var ad=1,bd=[],O=[],cd=[],dd=[],ed=[],Q=[],fd=[],K=[],gd=[],hd={},jd=4;
function R(a){kd||(kd=a)}function ld(a){for(var b=ad++,c=a.length;c<b;c++)a[c]=null;return b}function Hc(a,b){a.Nd||(a.Nd=a.getContext,a.getContext=function(d,e){e=a.Nd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?md(c,b):0}function md(a,b){var c=ld(K),d={handle:c,attributes:b,version:b.Ue,$d:a};a.canvas&&(a.canvas.ge=d);K[c]=d;("undefined"==typeof b.pf||b.pf)&&nd(d);return c}function Ic(a){od=K[a];h.Vd=L=od&&od.$d}
function nd(a){a||(a=od);if(!a.uf){a.uf=!0;var b=a.$d;Yc(b);Zc(b);$c(b);b.Xd=b.getExtension("EXT_disjoint_timer_query");b.cg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Gc={},kd,od,pd=a=>{var b=Ya(a)+1,c=D(b);c&&E(a,w,c,b);return c},qd=[],rd=(a,b)=>{qd.length=0;var c;for(b>>=2;c=w[a++];)b+=105!=c&b,qd.push(105==c?y[b]:(106==c?pa:B)[b++>>1]),++b;return qd},ud=a=>{var b=sd();a=a();td(b);return a},vd=0;function wd(){for(var a=S.length-1;0<=a;--a)xd(a);S=[];T=[]}var T=[];
function yd(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in T){var f=T[e];if(f.Ie==a&&d(f.Le,c))return}T.push({Ie:a,Ye:b,Le:c});T.sort(function(g,m){return g.Ye<m.Ye})}function zd(a){for(var b=0;b<T.length;++b)T[b].Ie==a&&(T.splice(b,1),--b)}function Ad(){return navigator.userActivation?navigator.userActivation.isActive:vd&&Bd.he}function Cd(){if(Ad())for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.Ie.apply(null,b.Le)}}
var S=[];function xd(a){var b=S[a];b.target.removeEventListener(b.Od,b.qf,b.Sd);S.splice(a,1)}function U(a){function b(d){++vd;Bd=a;Cd();a.Ud(d);Cd();--vd}if(!a.target)return-4;if(a.Td)a.qf=b,a.target.addEventListener(a.Od,b,a.Sd),S.push(a),Dd||(ta.push(wd),Dd=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].Od==a.Od&&xd(c--);return 0}function Ed(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function Fd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Gd={},Dd,Bd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td={},Ud=[0,document,window];function V(a){a=2<a?a?F(w,a):"":a;return Ud[a]||document.querySelector(a)}var Wd=a=>{var b=Ya(a)+1,c=Vd(b);E(a,w,c,b);return c},Xd=a=>ud(()=>{var b=Vd(8),c=b+4,d=Wd(a.id);if(d=V(d))y[b>>2]=d.width,y[c>>2]=d.height;return[y[b>>2],y[c>>2]]});function Yd(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Zd(a,b,c){a.Qf?ud(function(){var d=Wd(a.id);Yd(d,b,c)}):(a.width=b,a.height=c)}
function $d(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Zd(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=t,a.style.paddingTop=q,a.style.paddingBottom=u,a.style.marginLeft=x,a.style.marginRight=P,a.style.marginTop=
X,a.style.marginBottom=Y,document.body.style.margin=ub,document.documentElement.style.overflow=Va,document.body.scroll=Ke,a.style.ce=Le,a.ge&&a.ge.$d.viewport(0,0,d,e),Td.ne&&C.get(Td.ne)(37,0,Td.Me))}var c=Xd(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,t=a.style.paddingRight,q=a.style.paddingTop,u=a.style.paddingBottom,x=a.style.marginLeft,P=a.style.marginRight,X=a.style.marginTop,Y=a.style.marginBottom,ub=
document.body.style.margin,Va=document.documentElement.style.overflow,Ke=document.body.scroll,Le=a.style.ce;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function ae(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function be(a){return 0>Ud.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function ce(a,b){if(0!=b.He||0!=b.ze){$d(a);var c=b.Ef?innerWidth:screen.width,d=b.Ef?innerHeight:screen.height,e=be(a),f=e.width;e=e.height;var g=Xd(a),m=g[0];g=g[1];3==b.He?(ae(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.He&&(c*g<m*d?(f=g*c/m,ae(a,(d-f)/2,0),d=f):(f=m*d/g,ae(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.rf&&(a.style.ce="optimizeSpeed",
a.style.ce="-moz-crisp-edges",a.style.ce="-o-crisp-edges",a.style.ce="-webkit-optimize-contrast",a.style.ce="optimize-contrast",a.style.ce="crisp-edges",a.style.ce="pixelated");f=2==b.ze?devicePixelRatio:1;0!=b.ze&&(c=c*f|0,d=d*f|0,Zd(a,c,d),a.ge&&a.ge.$d.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Fd()?-3:-1;Td=b;b.ne&&C.get(b.ne)(37,0,b.Me);return 0}
function de(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function ee(a,b){B[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)B[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)B[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)y[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];y[a+1296>>2]=b.connected;y[a+1300>>2]=b.index;y[a+8>>2]=b.axes.length;y[a+12>>2]=b.buttons.length;E(b.id,w,a+1304,64);E(b.mapping,w,a+1368,64)}var fe=[];
function ge(a,b,c,d){for(var e=0;e<a;e++){var f=L[c](),g=f&&ld(d);f?(f.name=g,d[g]=f):R(1282);y[b+4*e>>2]=g}}function he(a,b,c,d,e,f,g,m){b=O[b];if(a=L[a](b,c))d=m&&E(a.name,w,m,d),e&&(y[e>>2]=d),f&&(y[f>>2]=a.size),g&&(y[g>>2]=a.type)}function ie(a,b){z[a>>2]=b;z[a+4>>2]=(b-z[a>>2])/4294967296}
function je(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:y[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:v[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:ie(b,
d);break;case 0:y[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:v[b>>0]=d?1:0}}else R(1281)}function ke(a,b,c){if(c){a=L.Xd.getQueryObjectEXT(gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;ie(c,d)}else R(1281)}function le(a,b,c){if(c){a=L.Xd.getQueryObjectEXT(gd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y[c>>2]=d}else R(1281)}function me(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function ne(a){var b=a.me,c=a.df,d;if(!b)for(a.me=b={},a.cf={},d=0;d<L.getProgramParameter(a,35718);++d){var e=L.getActiveUniform(a,d);var f=e.name;e=e.size;var g=me(f);g=0<g?f.slice(0,g):f;var m=a.Je;a.Je+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.cf[m++]=g}}function W(a){var b=L.jf;if(b){var c=b.me[a];"number"==typeof c&&(b.me[a]=c=L.getUniformLocation(b,b.cf[a]+(0<c?"["+c+"]":"")));return c}R(1282)}
function oe(a,b,c,d){if(c)if(a=O[a],ne(a),a=L.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:y[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:y[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else R(1281)}
function pe(a,b,c,d){if(c)if(a=L.getVertexAttrib(a,b),34975==b)y[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:y[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:y[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:y[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:y[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function qe(a,b,c,d,e){a-=5120;a=1==a?w:4==a?y:6==a?A:5==a||28922==a?z:oa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=jd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var re=[],se=[];function te(a,b){if(!Fd())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Ad()?ce(a,b):b.nf?(yd(ce,1,[a,b]),1):-2:-3:-4}
function ue(a,b){var c={target:V(2),Od:"beforeunload",Td:b,Ud:function(d=event){var e=C.get(b)(28,0,a);e&&(e=e?F(w,e):"");if(e)return d.preventDefault(),d.returnValue=e},Sd:!0};return U(c)}function ve(a,b,c,d,e,f){Id||(Id=D(256));a={target:V(a),Od:f,Td:d,Ud:function(g=event){var m=g.target.id?g.target.id:"",n=Id;E(Ed(g.target),w,n+0,128);E(m,w,n+128,128);C.get(d)(e,n,b)&&g.preventDefault()},Sd:c};return U(a)}
function we(a,b,c,d,e){Kd||(Kd=D(280));return U({target:a,Od:e,Td:d,Ud:function(f=event){var g=Kd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;y[g>>2]=n;y[g+4>>2]=Fd();var p=n?m:Jd,t=p&&p.id?p.id:"";E(Ed(p),w,g+8,128);E(t,w,g+136,128);y[g+264>>2]=p?p.clientWidth:0;y[g+268>>2]=p?p.clientHeight:0;y[g+272>>2]=screen.width;y[g+276>>2]=screen.height;n&&(Jd=m);C.get(d)(19,g,b)&&f.preventDefault()},Sd:c})}
function xe(a,b,c,d,e){Ld||(Ld=D(1432));b={target:V(2),he:!0,Od:e,Td:c,Ud:function(f=event){var g=Ld;ee(g,f.gamepad);C.get(c)(d,g,a)&&f.preventDefault()},Sd:b};return U(b)}
function ye(a,b,c,d,e,f){Md||(Md=D(176));a={target:V(a),he:!0,Od:f,Td:d,Ud:function(g){var m=Md;B[m>>3]=g.timeStamp;var n=m>>2;y[n+2]=g.location;y[n+3]=g.ctrlKey;y[n+4]=g.shiftKey;y[n+5]=g.altKey;y[n+6]=g.metaKey;y[n+7]=g.repeat;y[n+8]=g.charCode;y[n+9]=g.keyCode;y[n+10]=g.which;E(g.key||"",w,m+44,32);E(g.code||"",w,m+76,32);E(g.char||"",w,m+108,32);E(g.locale||"",w,m+140,32);C.get(d)(e,m,b)&&g.preventDefault()},Sd:c};return U(a)}
function ze(a,b,c){B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;na[2*a+20]=b.button;na[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=be(c);y[a+13]=b.clientX-c.left;y[a+14]=b.clientY-c.top}
function Ae(a,b,c,d,e,f){Nd||(Nd=D(72));a=V(a);return U({target:a,he:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Od:f,Td:d,Ud:function(g=event){ze(Nd,g,a);C.get(d)(e,Nd,b)&&g.preventDefault()},Sd:c})}function Be(a,b,c,d,e){Od||(Od=D(260));return U({target:a,Od:e,Td:d,Ud:function(f=event){var g=Od,m=document.pointerLockElement||document.Nd||document.ef||document.ye;y[g>>2]=!!m;var n=m&&m.id?m.id:"";E(Ed(m),w,g+4,128);E(n,w,g+132,128);C.get(d)(20,g,b)&&f.preventDefault()},Sd:c})}
function Ce(a,b,c,d){Pd||(Pd=D(36));a=V(a);return U({target:a,Od:"resize",Td:d,Ud:function(e=event){if(e.target==a){var f=document.body;if(f){var g=Pd;y[g>>2]=e.detail;y[g+4>>2]=f.clientWidth;y[g+8>>2]=f.clientHeight;y[g+12>>2]=innerWidth;y[g+16>>2]=innerHeight;y[g+20>>2]=outerWidth;y[g+24>>2]=outerHeight;y[g+28>>2]=pageXOffset;y[g+32>>2]=pageYOffset;C.get(d)(10,g,b)&&e.preventDefault()}}},Sd:c})}
function De(a,b,c,d,e,f){Qd||(Qd=D(1696));a=V(a);return U({target:a,he:"touchstart"==f||"touchend"==f,Od:f,Td:d,Ud:function(g){for(var m,n={},p=g.touches,t=0;t<p.length;++t)m=p[t],m.Re=m.Xe=0,n[m.identifier]=m;for(t=0;t<g.changedTouches.length;++t)m=g.changedTouches[t],m.Re=1,n[m.identifier]=m;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].Xe=1;p=Qd;B[p>>3]=g.timeStamp;var q=p>>2;y[q+3]=g.ctrlKey;y[q+4]=g.shiftKey;y[q+5]=g.altKey;y[q+6]=g.metaKey;q+=7;var u=be(a),x=0;for(t in n)if(m=
n[t],y[q]=m.identifier,y[q+1]=m.screenX,y[q+2]=m.screenY,y[q+3]=m.clientX,y[q+4]=m.clientY,y[q+5]=m.pageX,y[q+6]=m.pageY,y[q+7]=m.Re,y[q+8]=m.Xe,y[q+9]=m.clientX-u.left,y[q+10]=m.clientY-u.top,q+=13,31<++x)break;y[p+8>>2]=x;C.get(d)(e,p,b)&&g.preventDefault()},Sd:c})}
function Ee(a,b,c){var d=Ud[1];Rd||(Rd=D(8));return U({target:d,Od:"visibilitychange",Td:c,Ud:function(e=event){var f=Rd,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);y[f>>2]=document.hidden;y[f+4>>2]=g;C.get(c)(21,f,a)&&e.preventDefault()},Sd:b})}
function Fe(a,b,c,d){Sd||(Sd=D(104));return U({target:a,he:!0,Od:"wheel",Td:d,Ud:function(e=event){var f=Sd;ze(f,e,a);B[f+72>>3]=e.deltaX;B[f+80>>3]=e.deltaY;B[f+88>>3]=e.deltaZ;y[f+96>>2]=e.deltaMode;C.get(d)(9,f,b)&&e.preventDefault()},Sd:c})}
var Ge={},Ie=()=>{if(!He){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Ge)void 0===Ge[b]?delete a[b]:a[b]=Ge[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);He=c}return He},He;function Gb(a,b,c,d){a||(a=this);this.parent=a;this.Yd=a.Yd;this.je=null;this.id=yb++;this.name=b;this.mode=c;this.Id={};this.Jd={};this.ue=d}
Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},zf:{get:function(){return 16384===(this.mode&61440)}},Se:{get:function(){return 8192===(this.mode&61440)}}});Xb();zb=Array(4096);Nb(H,"/");I("/tmp",16895,0);I("/home",16895,0);I("/home/web_user",16895,0);
(()=>{I("/dev",16895,0);bb(259,{read:()=>0,write:(d,e,f,g)=>g});Ob("/dev/null",259);ab(1280,db);ab(1536,eb);Ob("/dev/tty",1280);Ob("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ta(a).byteLength);return a[--b]};J("/dev","random",c);J("/dev","urandom",c);I("/dev/shm",16895,0);I("/dev/shm/tmp",16895,0)})();
(()=>{I("/proc",16895,0);var a=I("/proc/self",16895,0);I("/proc/self/fd",16895,0);Nb({Yd:()=>{var b=jb(a,"fd",16895,73);b.Id={ie:(c,d)=>{var e=Kb(+d);c={parent:null,Yd:{Ve:"fake"},Id:{ke:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=Zb;h.FS_createDataFile=sb;h.FS_createPreloadedFile=rb;h.FS_unlink=Qb;h.FS_createLazyFile=bc;h.FS_createDevice=J;h.requestFullscreen=function(a,b){Mc(a,b)};h.requestAnimationFrame=function(a){oc(a)};
h.setCanvasSize=function(a,b,c){Oc(h.canvas,a,b);c||Pc()};h.pauseMainLoop=function(){kc=null;rc++};h.resumeMainLoop=function(){rc++;var a=gc,b=hc,c=ic;ic=null;pc(c,0,!1,qc,!0);fc(a,b);kc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return Fc(a,b,c,d)};for(var L,Z=0;32>Z;++Z)fe.push(Array(Z));var Je=new Float32Array(288);
for(Z=0;288>Z;++Z)re[Z]=Je.subarray(0,Z+1);var Me=new Int32Array(288);for(Z=0;288>Z;++Z)se[Z]=Me.subarray(0,Z+1);
var Se={G:function(a,b,c){dc=c;try{var d=Kb(a);switch(b){case 0:var e=ec();return 0>e?-28:Mb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ec(),d.flags|=e,0;case 5:return e=ec(),na[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return y[Ne()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof cc||"ErrnoError"!==f.name)throw f;return-f.ae}},Va:function(a,b,c){dc=c;try{var d=Kb(a);switch(b){case 21509:return d.Kd?0:-59;case 21505:if(!d.Kd)return-59;
if(d.Kd.Zd.wf){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=ec();y[e>>2]=25856;y[e+4>>2]=5;y[e+8>>2]=191;y[e+12>>2]=35387;for(var f=0;32>f;f++)v[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.Kd?0:-59;case 21506:case 21507:case 21508:if(!d.Kd)return-59;if(d.Kd.Zd.xf)for(e=ec(),b=[],f=0;32>f;f++)b.push(v[e+f+17>>0]);return 0;case 21519:if(!d.Kd)return-59;e=ec();return y[e>>2]=0;case 21520:return d.Kd?-28:-59;case 21531:e=ec();if(!d.Jd.vf)throw new G(59);
return d.Jd.vf(d,b,e);case 21523:if(!d.Kd)return-59;d.Kd.Zd.yf&&(f=[24,80],e=ec(),na[e>>1]=f[0],na[e+2>>1]=f[1]);return 0;case 21524:return d.Kd?0:-59;case 21515:return d.Kd?0:-59;default:return-28}}catch(g){if("undefined"==typeof cc||"ErrnoError"!==g.name)throw g;return-g.ae}},Wa:function(a,b,c,d){dc=d;try{b=b?F(w,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Kb(a).path;if(0==e.length)throw new G(44);b=Pa(f+"/"+e)}var g=d?ec():0;return Tb(b,c,g).fd}catch(m){if("undefined"==typeof cc||
"ErrnoError"!==m.name)throw m;return-m.ae}},Xa:()=>!0,Na:()=>{throw Infinity;},Hb:function(a){if(12448==a)return M=12288,1;M=12300;return 0},wc:function(a,b,c,d,e){if(62E3!=a)M=12296,c=0;else{if(b)for(;;){a=y[b>>2];if(12321==a)N.alpha=0<y[b+4>>2];else if(12325==a)N.depth=0<y[b+4>>2];else if(12326==a)N.stencil=0<y[b+4>>2];else if(12337==a)a=y[b+4>>2],N.antialias=0<a;else if(12338==a)a=y[b+4>>2],N.antialias=1==a;else if(12544==a)N.$f=12547!=y[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(y[e>>2]=
1),c&&0<d&&(y[c>>2]=62002),M=12288,c=1):(M=12300,c=0)}return c},Ia:function(a,b,c,d){if(62E3!=a)return M=12296,0;for(a=1;;){b=y[d>>2];if(12440==b)a=y[d+4>>2];else if(12344==b)break;else return M=12292,0;d+=8}if(2!=a)return M=12293,0;N.Ue=a-1;N.ag=0;Xc=Hc(h.canvas,N);if(0!=Xc)return M=12288,Ic(Xc),h.Gf=!0,Cc.forEach(function(e){e()}),Ic(null),62004;M=12297;return 0},Ka:function(a,b){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;M=12288;return 62006},Ja:function(a,b){if(62E3!=a)return M=
12296,0;if(62004!=b)return M=12294,0;a=Xc;od===K[a]&&(od=null);if("object"==typeof Gd)for(var c=K[a].$d.canvas,d=0;d<S.length;++d)S[d].target!=c||xd(d--);K[a]&&K[a].$d.canvas&&(K[a].$d.canvas.ge=void 0);K[a]=null;M=12288;Tc==b&&(Tc=0);return 1},La:function(a,b){if(62E3!=a)return M=12296,0;if(62006!=b)return M=12301,1;Uc==b&&(Uc=0);Vc==b&&(Vc=0);M=12288;return 1},Hc:function(a,b,c,d){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return y[d>>
2]=N.alpha?32:24,1;case 12321:return y[d>>2]=N.alpha?8:0,1;case 12322:return y[d>>2]=8,1;case 12323:return y[d>>2]=8,1;case 12324:return y[d>>2]=8,1;case 12325:return y[d>>2]=N.depth?24:0,1;case 12326:return y[d>>2]=N.stencil?8:0,1;case 12327:return y[d>>2]=12344,1;case 12328:return y[d>>2]=62002,1;case 12329:return y[d>>2]=0,1;case 12330:return y[d>>2]=4096,1;case 12331:return y[d>>2]=16777216,1;case 12332:return y[d>>2]=4096,1;case 12333:return y[d>>2]=0,1;case 12334:return y[d>>2]=0,1;case 12335:return y[d>>
2]=12344,1;case 12337:return y[d>>2]=N.antialias?4:0,1;case 12338:return y[d>>2]=N.antialias?1:0,1;case 12339:return y[d>>2]=4,1;case 12340:return y[d>>2]=12344,1;case 12341:case 12342:case 12343:return y[d>>2]=-1,1;case 12345:case 12346:return y[d>>2]=0,1;case 12347:return y[d>>2]=0,1;case 12348:return y[d>>2]=1;case 12349:case 12350:return y[d>>2]=0,1;case 12351:return y[d>>2]=12430,1;case 12352:return y[d>>2]=4,1;case 12354:return y[d>>2]=0,1;default:return M=12292,0}},J:function(){M=12288;return 62E3},
Ha:function(){return M},ac:function(a,b,c){if(62E3!=a)return M=12296,0;b&&(y[b>>2]=1);c&&(y[c>>2]=4);Sc=!0;M=12288;return 1},Ma:function(a,b,c,d){if(62E3!=a)return M=12296,0;if(0!=d&&62004!=d)return M=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return M=12301,0;Ic(d?Xc:null);Tc=d;Vc=b;Uc=c;M=12288;return 1},Fa:function(a,b){if(62E3!=a)return M=12296,0;M=12288;if(Wc[b])return Wc[b];switch(b){case 12371:a=pd("Emscripten");break;case 12372:a=pd("1.4 Emscripten EGL");break;case 12373:a=pd("");break;case 12429:a=
pd("OpenGL_ES");break;default:return M=12300,0}return Wc[b]=a},Ua:function(){if(Sc)if(h.Vd)if(h.Vd.isContextLost())M=12302;else return M=12288,1;else M=12290;else M=12289;return 0},$a:function(a,b){if(62E3!=a)return M=12296,0;0==b?fc(0,0):fc(1,b);M=12288;return 1},lc:function(a){if(62E3!=a)return M=12296,0;Vc=Uc=Tc=0;Sc=!1;M=12288;return 1},vb:function(){M=12288;return 1},kb:function(){M=12288;return 1},Ba:(a,b,c)=>{b=rd(b,c);return Ka[a].apply(null,b)},a:(a,b,c)=>{b=rd(b,c);return Ka[a].apply(null,
b)},H:function(){return Date.now()},ya:function(){if(!Fd())return-1;zd(ce);var a=Ud[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Da:function(){zd(de);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},d:function(){return devicePixelRatio},b:function(a,b,c){a=V(a);if(!a)return-4;a=be(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},i:function(a,b){if(0>
a||a>=Hd.length)return-5;if(!Hd[a])return-7;ee(b,Hd[a]);return 0},Pa:()=>w.length,f:mc,ea:function(){return Hd.length},Ea:function(a,b){y[a>>2]=screen.width;y[b>>2]=screen.height},da:function(a){L.activeTexture(a)},ca:function(a,b){L.attachShader(O[a],Q[b])},ua:function(a,b){L.Xd.beginQueryEXT(a,gd[b])},ba:function(a,b,c){L.bindAttribLocation(O[a],b,c?F(w,c):"")},aa:function(a,b){L.bindBuffer(a,bd[b])},$:function(a,b){L.bindFramebuffer(a,cd[b])},_:function(a,b){L.bindRenderbuffer(a,dd[b])},Z:function(a,
b){L.bindTexture(a,ed[b])},ma:function(a){L.bindVertexArray(fd[a])},Y:function(a,b,c,d){L.blendColor(a,b,c,d)},X:function(a){L.blendEquation(a)},W:function(a,b){L.blendEquationSeparate(a,b)},V:function(a,b){L.blendFunc(a,b)},U:function(a,b,c,d){L.blendFuncSeparate(a,b,c,d)},T:function(a,b,c,d){L.bufferData(a,c?w.subarray(c,c+b):b,d)},S:function(a,b,c,d){L.bufferSubData(a,b,w.subarray(d,d+c))},R:function(a){return L.checkFramebufferStatus(a)},Q:function(a){L.clear(a)},P:function(a,b,c,d){L.clearColor(a,
b,c,d)},O:function(a){L.clearDepth(a)},N:function(a){L.clearStencil(a)},M:function(a,b,c,d){L.colorMask(!!a,!!b,!!c,!!d)},td:function(a){L.compileShader(Q[a])},sd:function(a,b,c,d,e,f,g,m){L.compressedTexImage2D(a,b,c,d,e,f,m?w.subarray(m,m+g):null)},rd:function(a,b,c,d,e,f,g,m,n){L.compressedTexSubImage2D(a,b,c,d,e,f,g,n?w.subarray(n,n+m):null)},qd:function(a,b,c,d,e,f,g,m){L.copyTexImage2D(a,b,c,d,e,f,g,m)},pd:function(a,b,c,d,e,f,g,m){L.copyTexSubImage2D(a,b,c,d,e,f,g,m)},od:function(){var a=ld(O),
b=L.createProgram();b.name=a;b.re=b.pe=b.qe=0;b.Je=1;O[a]=b;return a},nd:function(a){var b=ld(Q);Q[b]=L.createShader(a);return b},md:function(a){L.cullFace(a)},ld:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=bd[d];e&&(L.deleteBuffer(e),e.name=0,bd[d]=null)}},kd:function(a,b){for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=cd[d];e&&(L.deleteFramebuffer(e),e.name=0,cd[d]=null)}},jd:function(a){if(a){var b=O[a];b?(L.deleteProgram(b),b.name=0,O[a]=null):R(1281)}},wa:function(a,b){for(var c=0;c<a;c++){var d=
y[b+4*c>>2],e=gd[d];e&&(L.Xd.deleteQueryEXT(e),gd[d]=null)}},id:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=dd[d];e&&(L.deleteRenderbuffer(e),e.name=0,dd[d]=null)}},hd:function(a){if(a){var b=Q[a];b?(L.deleteShader(b),Q[a]=null):R(1281)}},gd:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=ed[d];e&&(L.deleteTexture(e),e.name=0,ed[d]=null)}},la:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2];L.deleteVertexArray(fd[d]);fd[d]=null}},fd:function(a){L.depthFunc(a)},ed:function(a){L.depthMask(!!a)},
dd:function(a,b){L.depthRange(a,b)},cd:function(a,b){L.detachShader(O[a],Q[b])},bd:function(a){L.disable(a)},ad:function(a){L.disableVertexAttribArray(a)},$c:function(a,b,c){L.drawArrays(a,b,c)},ha:function(a,b,c,d){L.drawArraysInstanced(a,b,c,d)},ia:function(a,b){for(var c=fe[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];L.drawBuffers(c)},_c:function(a,b,c,d){L.drawElements(a,b,c,d)},ga:function(a,b,c,d,e){L.drawElementsInstanced(a,b,c,d,e)},Zc:function(a){L.enable(a)},Yc:function(a){L.enableVertexAttribArray(a)},
ta:function(a){L.Xd.endQueryEXT(a)},Xc:function(){L.finish()},Wc:function(){L.flush()},Vc:function(a,b,c,d){L.framebufferRenderbuffer(a,b,c,dd[d])},Uc:function(a,b,c,d,e){L.framebufferTexture2D(a,b,c,ed[d],e)},Tc:function(a){L.frontFace(a)},Sc:function(a,b){ge(a,b,"createBuffer",bd)},Qc:function(a,b){ge(a,b,"createFramebuffer",cd)},xa:function(a,b){for(var c=0;c<a;c++){var d=L.Xd.createQueryEXT();if(!d){for(R(1282);c<a;)y[b+4*c++>>2]=0;break}var e=ld(gd);d.name=e;gd[e]=d;y[b+4*c>>2]=e}},Pc:function(a,
b){ge(a,b,"createRenderbuffer",dd)},Oc:function(a,b){ge(a,b,"createTexture",ed)},ka:function(a,b){ge(a,b,"createVertexArray",fd)},Rc:function(a){L.generateMipmap(a)},Nc:function(a,b,c,d,e,f,g){he("getActiveAttrib",a,b,c,d,e,f,g)},Mc:function(a,b,c,d,e,f,g){he("getActiveUniform",a,b,c,d,e,f,g)},Lc:function(a,b,c,d){a=L.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);y[c>>2]=e;for(b=0;b<e;++b)y[d+4*b>>2]=Q.indexOf(a[b])},Kc:function(a,b){return L.getAttribLocation(O[a],b?F(w,b):"")},Jc:function(a,
b){je(a,b,4)},Ic:function(a,b,c){c?y[c>>2]=L.getBufferParameter(a,b):R(1281)},Gc:function(){var a=L.getError()||kd;kd=0;return a},Fc:function(a,b){je(a,b,2)},Ec:function(a,b,c,d){a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;y[d>>2]=a},Dc:function(a,b){je(a,b,0)},Bc:function(a,b,c,d){a=L.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,w,d,b):0;c&&(y[c>>2]=b)},Cc:function(a,b,c){if(c)if(a>=ad)R(1281);else if(a=
O[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.re)for(b=0;b<L.getProgramParameter(a,35718);++b)a.re=Math.max(a.re,L.getActiveUniform(a,b).name.length+1);y[c>>2]=a.re}else if(35722==b){if(!a.pe)for(b=0;b<L.getProgramParameter(a,35721);++b)a.pe=Math.max(a.pe,L.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.pe}else if(35381==b){if(!a.qe)for(b=0;b<L.getProgramParameter(a,35382);++b)a.qe=Math.max(a.qe,L.getActiveUniformBlockName(a,b).length+
1);y[c>>2]=a.qe}else y[c>>2]=L.getProgramParameter(a,b);else R(1281)},oa:ke,qa:le,na:ke,pa:le,ra:function(a,b,c){c?y[c>>2]=L.Xd.getQueryEXT(a,b):R(1281)},Ac:function(a,b,c){c?y[c>>2]=L.getRenderbufferParameter(a,b):R(1281)},yc:function(a,b,c,d){a=L.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,w,d,b):0;c&&(y[c>>2]=b)},xc:function(a,b,c,d){a=L.getShaderPrecisionFormat(a,b);y[c>>2]=a.rangeMin;y[c+4>>2]=a.rangeMax;y[d>>2]=a.precision},vc:function(a,b,c,d){if(a=L.getShaderSource(Q[a]))b=
0<b&&d?E(a,w,d,b):0,c&&(y[c>>2]=b)},zc:function(a,b,c){c?35716==b?(a=L.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(Q[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=L.getShaderParameter(Q[a],b):R(1281)},uc:function(a){var b=hd[a];if(!b){switch(a){case 7939:b=L.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=pd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||R(1280);b=b&&pd(b);break;
case 7938:b=pd("OpenGL ES 2.0 ("+L.getParameter(7938)+")");break;case 35724:b=L.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=pd(b);break;default:R(1280)}hd[a]=b}return b},tc:function(a,b,c){c?A[c>>2]=L.getTexParameter(a,b):R(1281)},sc:function(a,b,c){c?y[c>>2]=L.getTexParameter(a,b):R(1281)},pc:function(a,b){b=b?F(w,b):"";if(a=O[a]){ne(a);var c=a.me,d=0,e=b,f=me(b);0<f&&(d=parseInt(b.slice(f+
1))>>>0,e=b.slice(0,f));if((e=a.df[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else R(1281);return-1},rc:function(a,b,c){oe(a,b,c,2)},qc:function(a,b,c){oe(a,b,c,0)},mc:function(a,b,c){c?y[c>>2]=L.getVertexAttribOffset(a,b):R(1281)},oc:function(a,b,c){pe(a,b,c,2)},nc:function(a,b,c){pe(a,b,c,5)},kc:function(a,b){L.hint(a,b)},jc:function(a){return(a=bd[a])?L.isBuffer(a):0},ic:function(a){return L.isEnabled(a)},hc:function(a){return(a=cd[a])?L.isFramebuffer(a):0},gc:function(a){return(a=
O[a])?L.isProgram(a):0},va:function(a){return(a=gd[a])?L.Xd.isQueryEXT(a):0},fc:function(a){return(a=dd[a])?L.isRenderbuffer(a):0},ec:function(a){return(a=Q[a])?L.isShader(a):0},dc:function(a){return(a=ed[a])?L.isTexture(a):0},ja:function(a){return(a=fd[a])?L.isVertexArray(a):0},cc:function(a){L.lineWidth(a)},bc:function(a){a=O[a];L.linkProgram(a);a.me=0;a.df={}},$b:function(a,b){3317==a&&(jd=b);L.pixelStorei(a,b)},_b:function(a,b){L.polygonOffset(a,b)},sa:function(a,b){L.Xd.queryCounterEXT(gd[a],
b)},Zb:function(a,b,c,d,e,f,g){(g=qe(f,e,c,d,g))?L.readPixels(a,b,c,d,e,f,g):R(1280)},Yb:function(){},Xb:function(a,b,c,d){L.renderbufferStorage(a,b,c,d)},Wb:function(a,b){L.sampleCoverage(a,!!b)},Vb:function(a,b,c,d){L.scissor(a,b,c,d)},Ub:function(){R(1280)},Tb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?y[d+4*f>>2]:-1,m=y[c+4*f>>2];g=m?F(w,m,0>g?void 0:g):"";e+=g}L.shaderSource(Q[a],e)},Sb:function(a,b,c){L.stencilFunc(a,b,c)},Rb:function(a,b,c,d){L.stencilFuncSeparate(a,b,c,d)},Qb:function(a){L.stencilMask(a)},
Pb:function(a,b){L.stencilMaskSeparate(a,b)},Ob:function(a,b,c){L.stencilOp(a,b,c)},Nb:function(a,b,c,d){L.stencilOpSeparate(a,b,c,d)},Mb:function(a,b,c,d,e,f,g,m,n){L.texImage2D(a,b,c,d,e,f,g,m,n?qe(m,g,d,e,n):null)},Lb:function(a,b,c){L.texParameterf(a,b,c)},Kb:function(a,b,c){L.texParameterf(a,b,A[c>>2])},Jb:function(a,b,c){L.texParameteri(a,b,c)},Ib:function(a,b,c){L.texParameteri(a,b,y[c>>2])},Gb:function(a,b,c,d,e,f,g,m,n){var p=null;n&&(p=qe(m,g,e,f,n));L.texSubImage2D(a,b,c,d,e,f,g,m,p)},
Fb:function(a,b){L.uniform1f(W(a),b)},Eb:function(a,b,c){if(288>=b)for(var d=re[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);L.uniform1fv(W(a),d)},Db:function(a,b){L.uniform1i(W(a),b)},Cb:function(a,b,c){if(288>=b)for(var d=se[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);L.uniform1iv(W(a),d)},Bb:function(a,b,c){L.uniform2f(W(a),b,c)},Ab:function(a,b,c){if(144>=b)for(var d=re[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>
2,c+8*b>>2);L.uniform2fv(W(a),d)},zb:function(a,b,c){L.uniform2i(W(a),b,c)},yb:function(a,b,c){if(144>=b)for(var d=se[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);L.uniform2iv(W(a),d)},xb:function(a,b,c,d){L.uniform3f(W(a),b,c,d)},ub:function(a,b,c){if(96>=b)for(var d=re[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);L.uniform3fv(W(a),d)},tb:function(a,b,c,d){L.uniform3i(W(a),
b,c,d)},sb:function(a,b,c){if(96>=b)for(var d=se[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);L.uniform3iv(W(a),d)},rb:function(a,b,c,d,e){L.uniform4f(W(a),b,c,d,e)},qb:function(a,b,c){if(72>=b){var d=re[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);L.uniform4fv(W(a),d)},pb:function(a,b,c,d,e){L.uniform4i(W(a),b,c,d,e)},ob:function(a,
b,c){if(72>=b)for(var d=se[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);L.uniform4iv(W(a),d)},nb:function(a,b,c,d){if(72>=b)for(var e=re[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);L.uniformMatrix2fv(W(a),!!c,e)},mb:function(a,b,c,d){if(32>=b)for(var e=re[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+
(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);L.uniformMatrix3fv(W(a),!!c,e)},lb:function(a,b,c,d){if(18>=b){var e=re[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+
11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);L.uniformMatrix4fv(W(a),!!c,e)},jb:function(a){a=O[a];L.useProgram(a);L.jf=a},ib:function(a){L.validateProgram(O[a])},hb:function(a,b){L.vertexAttrib1f(a,b)},gb:function(a,b){L.vertexAttrib1f(a,A[b>>2])},fb:function(a,b,c){L.vertexAttrib2f(a,b,c)},eb:function(a,b){L.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},db:function(a,b,c,d){L.vertexAttrib3f(a,b,c,d)},cb:function(a,b){L.vertexAttrib3f(a,A[b>>2],A[b+
4>>2],A[b+8>>2])},bb:function(a,b,c,d,e){L.vertexAttrib4f(a,b,c,d,e)},ab:function(a,b){L.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},fa:function(a,b){L.vertexAttribDivisor(a,b)},_a:function(a,b,c,d,e,f){L.vertexAttribPointer(a,b,c,!!d,e,f)},Za:function(a,b,c,d){L.viewport(a,b,c,d)},h:()=>0,Ya:(a,b,c)=>w.copyWithin(a,b,b+c),za:function(a,b,c){return te(a,{He:y[c>>2],ze:y[c+4>>2],rf:y[c+8>>2],nf:b,ne:y[c+12>>2],Me:y[c+16>>2]})},E:function(a,b){a=V(a);return a?a.requestPointerLock?Ad()?
de(a):b?(yd(de,2,[a]),1):-2:-1:-4},Oa:()=>{l("OOM")},j:function(){return(Hd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},k:function(a,b,c){return"undefined"==typeof onbeforeunload?-1:1!==c?-5:ue(a,b)},w:function(a,b,c,d){return ve(a,b,c,d,12,"blur")},c:Yd,e:function(a,b,c){a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},x:function(a,b,c,d){return ve(a,b,c,d,13,"focus")},n:function(a,b,c,d){if(!Fd())return-1;
a=V(a);if(!a)return-4;we(a,b,c,d,"webkitfullscreenchange");return we(a,b,c,d,"fullscreenchange")},L:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?xe(a,b,c,26,"gamepadconnected"):-1},K:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?xe(a,b,c,27,"gamepaddisconnected"):-1},q:function(a,b,c,d){return ye(a,b,c,d,2,"keydown")},o:function(a,b,c,d){return ye(a,b,c,d,1,"keypress")},p:function(a,b,c,d){return ye(a,b,c,d,3,"keyup")},vd:function(a,b,c){a=
C.get(a);pc(a,b,c)},C:function(a,b,c,d){return Ae(a,b,c,d,5,"mousedown")},A:function(a,b,c,d){return Ae(a,b,c,d,33,"mouseenter")},z:function(a,b,c,d){return Ae(a,b,c,d,34,"mouseleave")},D:function(a,b,c,d){return Ae(a,b,c,d,8,"mousemove")},B:function(a,b,c,d){return Ae(a,b,c,d,6,"mouseup")},r:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Nd||document.body.ef||document.body.ye))return-1;a=V(a);if(!a)return-4;Be(a,b,c,d,"mozpointerlockchange");Be(a,
b,c,d,"webkitpointerlockchange");Be(a,b,c,d,"mspointerlockchange");return Be(a,b,c,d,"pointerlockchange")},m:function(a,b,c,d){return Ce(a,b,c,d)},s:function(a,b,c,d){return De(a,b,c,d,25,"touchcancel")},u:function(a,b,c,d){return De(a,b,c,d,23,"touchend")},t:function(a,b,c,d){return De(a,b,c,d,24,"touchmove")},v:function(a,b,c,d){return De(a,b,c,d,22,"touchstart")},l:function(a,b,c){return Ee(a,b,c)},y:function(a,b,c,d){return(a=V(a))?"undefined"!=typeof a.onwheel?Fe(a,b,c,d):-1:-4},Aa:function(a){ha(a?
F(w,a):"")},g:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ra:(a,b)=>{var c=0;Ie().forEach(function(d,e){var f=b+c;e=z[a+4*e>>2]=f;for(f=0;f<d.length;++f)v[e++>>0]=d.charCodeAt(f);v[e>>0]=0;c+=d.length+1});return 0},Sa:(a,b)=>{var c=Ie();z[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});z[b>>2]=d;return 0},I:function(a){try{var b=Kb(a);Ub(b);return 0}catch(c){if("undefined"==typeof cc||"ErrnoError"!==
c.name)throw c;return c.ae}},Ta:function(a,b,c,d){try{a:{var e=Kb(a);a=b;for(var f,g=b=0;g<c;g++){var m=z[a>>2],n=z[a+4>>2];a+=8;var p=e,t=m,q=n,u=f,x=v;if(0>q||0>u)throw new G(28);if(null===p.fd)throw new G(8);if(1===(p.flags&2097155))throw new G(8);if(16384===(p.node.mode&61440))throw new G(31);if(!p.Jd.read)throw new G(28);var P="undefined"!=typeof u;if(!P)u=p.position;else if(!p.seekable)throw new G(70);var X=p.Jd.read(p,x,t,q,u);P||(p.position+=X);var Y=X;if(0>Y){var ub=-1;break a}b+=Y;if(Y<
n)break;"undefined"!==typeof f&&(f+=Y)}ub=b}z[d>>2]=ub;return 0}catch(Va){if("undefined"==typeof cc||"ErrnoError"!==Va.name)throw Va;return Va.ae}},Qa:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(b))return 61;var e=Kb(a);Vb(e,b,c);pa[d>>3]=BigInt(e.position);e.De&&0===b&&0===c&&(e.De=null);return 0}catch(f){if("undefined"==typeof cc||"ErrnoError"!==f.name)throw f;return f.ae}},F:function(a,b,c,d){try{a:{var e=
Kb(a);a=b;for(var f,g=b=0;g<c;g++){var m=z[a>>2],n=z[a+4>>2];a+=8;var p=Wb(e,v,m,n,f);if(0>p){var t=-1;break a}b+=p;"undefined"!==typeof f&&(f+=p)}t=b}z[d>>2]=t;return 0}catch(q){if("undefined"==typeof cc||"ErrnoError"!==q.name)throw q;return q.ae}},ud:Oe,Ga:Pe,wb:Qe,Ca:Re};
(function(){function a(c){r=c=c.exports;ka=r.wd;var d=ka.buffer;h.HEAP8=v=new Int8Array(d);h.HEAP16=na=new Int16Array(d);h.HEAP32=y=new Int32Array(d);h.HEAPU8=w=new Uint8Array(d);h.HEAPU16=oa=new Uint16Array(d);h.HEAPU32=z=new Uint32Array(d);h.HEAPF32=A=new Float32Array(d);h.HEAPF64=B=new Float64Array(d);h.HEAP64=pa=new BigInt64Array(d);h.HEAPU64=new BigUint64Array(d);C=r.yd;ra.unshift(r.xd);Aa("wasm-instantiate");return c}var b={a:Se};za("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,
a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Ha(b,function(c){a(c.instance)});return{}})();var Te=h._main=(a,b)=>(Te=h._main=r.zd)(a,b),D=a=>(D=r.Ad)(a),Ne=()=>(Ne=r.Bd)(),fb=(a,b)=>(fb=r.Cd)(a,b),Ue=(a,b)=>(Ue=r.Dd)(a,b),sd=()=>(sd=r.Ed)(),td=a=>(td=r.Fd)(a),Vd=a=>(Vd=r.Gd)(a);function Oe(a,b,c){var d=sd();try{return C.get(a)(b,c)}catch(e){td(d);if(e!==e+0)throw e;Ue(1,0)}}
function Qe(a,b,c,d,e){var f=sd();try{return C.get(a)(b,c,d,e)}catch(g){td(f);if(g!==g+0)throw g;Ue(1,0)}}function Pe(a,b,c,d){var e=sd();try{return C.get(a)(b,c,d)}catch(f){td(e);if(f!==f+0)throw f;Ue(1,0)}}function Re(a,b){var c=sd();try{C.get(a)(b)}catch(d){td(c);if(d!==d+0)throw d;Ue(1,0)}}h.addRunDependency=za;h.removeRunDependency=Aa;h.FS_createPath=Zb;h.FS_createDataFile=sb;h.FS_createLazyFile=bc;h.FS_createDevice=J;h.FS_unlink=Qb;h.FS_createPreloadedFile=rb;var Ve;
ya=function We(){Ve||Xe();Ve||(ya=We)};
function Xe(){function a(){if(!Ve&&(Ve=!0,h.calledRun=!0,!la)){h.noFSInit||Yb||(Yb=!0,Xb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?J("/dev","stdin",h.stdin):Pb("/dev/tty","/dev/stdin"),h.stdout?J("/dev","stdout",null,h.stdout):Pb("/dev/tty","/dev/stdout"),h.stderr?J("/dev","stderr",null,h.stderr):Pb("/dev/tty1","/dev/stderr"),Tb("/dev/stdin",0),Tb("/dev/stdout",1),Tb("/dev/stderr",1));Ab=!1;Na(ra);Na(sa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(Ye){var b=Te;try{var c=
b(0,0);ma=c;yc(c)}catch(d){xc(d)}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),ua.unshift(b);Na(ua)}}if(!(0<wa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();Na(qa);0<wa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();
var Ye=!0;h.noInitialRun&&(Ye=!1);Xe();
